#!/bin/bash

# This script creates an archive with the source files of Solarus
# Tools (editor & validator).
# Usage: ./make_solarus_tools_src_package version_number

app="solarus_tools"
if [ $# != 1 ];
then
  echo "Usage: $0 version_number"
  exit 1
fi

version=$1

rm -rf ${app}-${version}
mkdir ${app}-${version}
git archive -o ${app}-${version}/tmp.tar HEAD tools
cd ${app}-${version}
tar xf tmp.tar
rm tmp.tar
mv -T tools ../${app}-${version}-x
cd ..
rm -rf ${app}-${version}
mv -T ${app}-${version}-x ${app}-${version}
rm -f ${app}-${version}-src.tar.gz
tar czf ${app}-${version}-src.tar.gz ${app}-${version}
rm -rf ${app}-${version}