#!/bin/bash

# This script creates an archive with the linux32 binary files for zsxd.
# The binary files are assumed to be already compiled.
# Usage: ./make_zsxd_linux32 version_number

if [ $# != 1 ];
then
  echo "Usage: ./make_zsxd_linux32 version_number"
  exit 1
fi

version=$1

rm -rf zsxd-$version
mkdir zsxd-$version
cp src/solarus quests/zsxd/data/data.solarus cmake/linux32/readme.txt license.txt zsxd-$version
tar czf zsxd-$version-linux32.tar.gz zsxd-$version

