[outside_world.village.welcome_sign]
#       |-----------------------|
line1 = "       Bienvenue"
line2 = "       à Lyriann"

[outside_world.village.monkey]
#       |-----------------------|
line1 = "Au secours ! Depuis"
line2 = "cette nuit, tout le"
line3 = "monde a peur !"
next = outside_world.village.monkey.2

[outside_world.village.monkey.2]
#       |-----------------------|
line1 = "Le village a été"
line2 = "encerclé par des"
line3 = "monstres !"

[outside_world.village.monkey.without_shield]
#       |-----------------------|
line1 = "Je ne sais pas ce qui"
line2 = "se passe, mais si tu"
line3 = "veux mon avis, tu ne"
next = outside_world.village.monkey.without_shield.2

[outside_world.village.monkey.without_shield.2]
#       |-----------------------|
line1 = "devrais pas t'aventurer"
line2 = "dehors sans protection."

[outside_world.village.monkey.with_shield]
#       |-----------------------|
line1 = "Je ne sais pas ce qui"
line2 = "se passe, mais si tu"
line3 = "veux mon avis, ton"
next = outside_world.village.monkey.with_shield.2

[outside_world.village.monkey.with_shield.2]
#       |-----------------------|
line1 = "Bouclier ne sera pas de"
line2 = "trop... Sois prudent !"

[outside_world.village.grand_son_npc]
#       |-----------------------|
line1 = "Si tu ne sais plus quoi"
line2 = "faire, tu devrais aller"
line3 = "voir Mamie, elle adore"
next = outside_world.village.grand_son_npc.2
cancel = all

[outside_world.village.grand_son_npc.2]
#       |-----------------------|
line1 = "donner des conseils."
line2 = "J'en sais pas plus, je"
line3 = "ne suis qu'un gosse !"

[outside_world.village.chignon_woman_npc]
#       |-----------------------|
line1 = "Quand l'icône bleue"
line2 = "apparaît, elle indique"
line3 = "ce que tu peux faire en"
next = outside_world.village.chignon_woman_npc.2
cancel = all

[outside_world.village.chignon_woman_npc.2]
#       |-----------------------|
line1 = "appuyant sur la touche"
line2 = "Action (espace)."
line3 = "Pense à l'observer pour"
next = outside_world.village.chignon_woman_npc.3

[outside_world.village.chignon_woman_npc.3]
#       |-----------------------|
line1 = "savoir quand tu peux"
line2 = "interagir avec ton"
line3 = "environnement !"

# TODO
#       |-----------------------|
#line1 = "Il paraît que chaque"
#line2 = "donjon du monde cache"
#line3 = "un Fragment de Coeur..."
#next = outside_world.village.chignon_woman_npc.2
#cancel = all

[outside_world.village.chignon_woman_npc.2]
#       |-----------------------|
line1 = "Intriguant, non ?"

[outside_world.village.cliff_man_npc]
#       |-----------------------|
line1 = "Sais-tu que tu peux"
line2 = "sauter de certaines"
line3 = "falaises ? Ca pourrait"
next = outside_world.village.cliff_man_npc.2
cancel = all

[outside_world.village.cliff_man_npc.2]
#       |-----------------------|
line1 = "te permettre d'attein-"
line2 = "dre des endroits"
line3 = "difficiles d'accès."

[outside_world.village.hat_man_npc]
#       |-----------------------|
line1 = "Si tu manques d'argent,"
line2 = "je ne te conseille pas"
line3 = "d'aller à la Maison des"
next = outside_world.village.hat_man_npc.2
cancel = all

[outside_world.village.hat_man_npc.2]
#       |-----------------------|
line1 = "Rubis, car tu risques"
line2 = "de dilapider toutes tes"
line3 = "économies !"
next = outside_world.village.hat_man_npc.3

[outside_world.village.hat_man_npc.3]
#       |-----------------------|
line1 = "Quoique, tu as l'air"
line2 = "plus doué que moi."
next = outside_world.village.hat_man_npc.4

[outside_world.village.hat_man_npc.4]
#       |-----------------------|
line1 = "Peut-être que tu sauras"
line2 = "mieux t'en sortir !"

[outside_world.village.rupee_house_sign]
#       |-----------------------|
line1 = "  - Maison des Rubis -"
line2 = "Gagnez de l'argent"
line3 = "tout en vous amusant !"

[outside_world.village.waterfall_sign]
#       |-----------------------|
line1 = "Servez-vous de notre"
line2 = "eau fraîche de la"
line3 = "cascade !"
next = outside_world.village.waterfall_sign.2

[outside_world.village.waterfall_sign.2]
#       |-----------------------|
line1 = "  Office de Tourisme"
line2 = "      de Lyriann"

[outside_world.village.pastry_shop_sign]
#       |-----------------------|
line1 = "Pâtisserie"

[outside_world.village.shop_sign]
#       |-----------------------|
line1 = "Boutique"

[outside_world.village.letter_box]
#       |-----------------------|
line1 = "Ca ne se fait pas de"
line2 = "fouiller dans la boîte"
line3 = "aux lettres des gens !" 

[outside_world.warning_holes_sign]
#       |-----------------------|
line1 = "Attention aux trous !"

[outside_world.flower_hole_sign]
#       |-----------------------|
line1 = "Le trou près de la"
line2 = "fleur n'est pas aussi"
line3 = "dangereux"
next = outside_world.flower_hole_sign.2

[outside_world.flower_hole_sign.2]
#       |-----------------------|
line1 = "qu'il en a l'air..."

[outside_world.telepathic_booth_sign]
#       |-----------------------|
line1 = "Cabine télépathique"

[outside_world.surprise_wall_sign]
#       |-----------------------|
line1 = " - Mur aux surprises -"
line2 = "Venez tenter votre"
line3 = "chance et remportez"
next = outside_world.surprise_wall_sign.2

[outside_world.surprise_wall_sign.2]
#       |-----------------------|
line1 = "le trésor caché !"

[outside_world.billy_cavern_sign]
#       |-----------------------|
line1 = "Caverne de Billy le"
line2 = "Téméraire."
line3 = "Entrée interdite !"

[outside_world.beaumont_hill_sign]
#       |-----------------------|
line1 = "Celui qui plantera un"
line2 = "edelweiss au sommet de"
line3 = "la colline de Beaumont"
next = outside_world.beaumont_hill_sign.2

[outside_world.beaumont_hill_sign.2]
#       |-----------------------|
line1 = "passera une bonne"
line2 = "journée."

[rupee_house.game_1.intro]
#       |-----------------------|
line1 = "Bienvenue au jeu du"
line2 = "coffre-mystère. Paie 20"
line3 = "rubis pour ouvrir l'un"
next = rupee_house.game_1.intro.2

[rupee_house.game_1.intro.2]
#       |-----------------------|
line1 = "des trois coffres et"
line2 = "tenter de remporter"
line3 = "plus de rubis !"
next = rupee_house.game_1.intro.3

[rupee_house.game_1.intro.3]
#       |-----------------------|
line1 = "Alors, tu veux jouer ?"
line2 = "Oui"
line3 = "Non"
question = true

[rupee_house.game_1.choose_chest]
#       |-----------------------|
line1 = "Va choisir l'un des"
line2 = "trois coffres !"
next = rupee_house.game_1.choose_chest.2

[rupee_house.game_1.choose_chest.2]
#       |-----------------------|
line1 = "Mais ne compte pas sur"
line2 = "moi pour t'aider !"

[rupee_house.game_1.good_luck]
#       |-----------------------|
line1 = "Va choisir un coffre"
line2 = "et bonne chance !"

[rupee_house.game_1.not_allowed_to_play]
#       |-----------------------|
line1 = "Tu as déjà assez gagné"
line2 = "non ? Nous sommes"
line3 = "ruinés à cause de toi !"

[rupee_house.game_1.play_again_question]
#       |-----------------------|
line1 = "Tu veux retenter ta"
line2 = "chance ?"
next = rupee_house.game_1.play_again_question.2

[rupee_house.game_1.play_again_question.2]
#       |-----------------------|
line1 = "C'est 20 rubis !"
line2 = "Oui"
line3 = "Non"
question = true

[rupee_house.game_1.not_playing]
#       |-----------------------|
line1 = "Vis ta vie ! Sois"
line2 = "un peu plus motivé !"

[rupee_house.game_2.intro]
#       |-----------------------|
line1 = "Bienvenue au tout"
line2 = "nouveau jeu du"
line3 = "bandit manchot !"
next = rupee_house.game_2.intro.2

[rupee_house.game_2.intro.2]
#       |-----------------------|
line1 = "Mise 5 ou 20 rubis et"
line2 = "tente d'aligner trois"
line3 = "symboles identiques"
next = rupee_house.game_2.intro.3

[rupee_house.game_2.intro.3]
#       |-----------------------|
line1 = "pour gagner plusieurs"
line2 = "fois ta mise !"
line3 = ""
next = rupee_house.game_2.intro.4

[rupee_house.game_2.intro.4]
#       |-----------------------|
line1 = "Alors, tu veux jouer ?"
line2 = "Oui"
line3 = "Non"
question = true

[rupee_house.game_2.not_playing]
#       |-----------------------|
line1 = "Une autre fois"
line2 = "peut-être ?"

[rupee_house.game_2.choose_bet]
#       |-----------------------|
line1 = "Combien veux-tu miser ?"
line2 = "5 rubis"
line3 = "20 rubis"
question = true

[rupee_house.game_2.just_paid]
#       |-----------------------|
line1 = "Merci !"
next = rupee_house.game_2.playing

[rupee_house.game_2.playing]
#       |-----------------------|
line1 = "Approche-toi des"
line2 = "roulettes et appuie sur"
line3 = "la touche action"
next = rupee_house.game_2.playing.2

[rupee_house.game_2.playing.2]
#       |-----------------------|
line1 = "pour les arrêter."
line2 = "Bonne chance !"

[rupee_house.game_2.reward.same_any]
#       |-----------------------|
line1 = "Trois symboles identi-"
line2 = "ques, pas mal ! Tu"
line3 = "gagnes 4 fois ta mise."

[rupee_house.game_2.reward.green_rupees]
#       |-----------------------|
line1 = "Trois rubis verts,"
line2 = "joli ! Tu remportes"
line3 = "5 fois ta mise !"

[rupee_house.game_2.reward.blue_rupees]
#       |-----------------------|
line1 = "Trois rubis bleus !"
line2 = "Félicitations, tu"
line3 = "repars avec pas moins"
next = rupee_house.game_2.reward.blue_rupees.2

[rupee_house.game_2.reward.blue_rupees.2]
#       |-----------------------|
line1 = "de 7 fois ta mise !"

[rupee_house.game_2.reward.red_rupees]
#       |-----------------------|
line1 = "Trois rubis rouges !!!"
line2 = "Je suis très"
line3 = "impressionné !"
next = rupee_house.game_2.reward.red_rupees.2

[rupee_house.game_2.reward.red_rupees.2]
#       |-----------------------|
line1 = "Tu repars avec 10 fois"
line2 = "ta mise. Bravo !"

[rupee_house.game_2.reward.different_rupees]
#       |-----------------------|
line1 = "Whaou !!! Tu as obtenu"
line2 = "trois rubis de couleurs"
line3 = "différentes, c'est pas"
next = rupee_house.game_2.reward.different_rupees.2

[rupee_house.game_2.reward.reward.different_rupees.2]
#       |-----------------------|
line1 = "tous les jours qu'on"
line2 = "voit ça ! Tu remportes"
line3 = "15 fois ta mise."

[rupee_house.game_2.reward.yoshi]
#       |-----------------------|
line1 = "$1...$3Trois Yoshi ?!"
line2 = "C'est à peine"
line3 = "croyable ! C'est la"
next = rupee_house.game_2.reward.yoshi.2

[rupee_house.game_2.reward.yoshi.2]
#       |-----------------------|
line1 = "meilleure combinaison"
line2 = "possible... Tu gagnes"
line3 = "20 fois ta mise !"

[rupee_house.game_2.reward.none]
#       |-----------------------|
line1 = "Pas de chance, tu n'as"
line2 = "formé aucune"
line3 = "combinaison."
next = rupee_house.game_2.reward.none.2

[rupee_house.game_2.reward.none.2]
#       |-----------------------|
line1 = "Tu veux réessayer ?"
line2 = "Oui"
line3 = "Non"
question = true

[rupee_house.game_3.intro]
#       |-----------------------|
line1 = "Le but du jeu est de"
line2 = "traverser le labyrinthe"
line3 = "dans un temps limité"
next = rupee_house.game_3.intro.2

[rupee_house.game_3.intro.2]
#       |-----------------------|
line1 = "puis de pousser les"
line2 = "blocs pour te frayer un"
line3 = "chemin. Cela ne te"
next = rupee_house.game_3.intro.3

[rupee_house.game_3.intro.3]
#       |-----------------------|
line1 = "coûtera que 10 rubis"
line2 = "et il y a un Fragment"
line3 = "de Coeur à gagner !"
next = rupee_house.game_3.intro.4

[rupee_house.game_3.intro.4]
#       |-----------------------|
line1 = "Alors, tu veux jouer ?"
line2 = "Oui"
line3 = "Non"
question = true

[rupee_house.game_3.go]
#       |-----------------------|
line1 = "Et c'est parti !"
line2 = "Bonne chance !"

[rupee_house.game_3.not_playing]
#       |-----------------------|
line1 = "C'est toi qui vois !"

[rupee_house.game_3.not_allowed_to_play]
#       |-----------------------|
line1 = "Désolé, tu as déjà"
line2 = "gagné à ce jeu !"

[rupee_house.game_3.restart_question]
#       |-----------------------|
line1 = "Tu veux recommencer à"
line2 = "zéro ?"
next = rupee_house.game_3.restart_question.2

[rupee_house.game_3.restart_question.2]
#       |-----------------------|
line1 = "C'est 10 rubis !"
line2 = "Oui"
line3 = "Non"
question = true

[rupee_house.not_enough_money]
#       |-----------------------|
line1 = "Tu n'as pas assez"
line2 = "d'argent !"

[rupee_house.pay_first]
#       |-----------------------|
line1 = "Hé ! Ici il faut payer"
line2 = "avant de jouer !"

[grandma_house.sword]
#       |-----------------------|
line1 = "Les monstres envahis-"
line2 = "sent la plaine. C'est"
line3 = "mauvais signe : j'ai"
next = grandma_house.sword.2
cancel = all

[grandma_house.sword.2]
#       |-----------------------|
line1 = "peur que quelque chose"
line2 = "de grave soit arrivé."
next = grandma_house.sword.3

[grandma_house.sword.3]
#       |-----------------------|
line1 = "Tu cherches une épée ?"
line2 = "Tu devrais aller voir"
line3 = "le forgeron dans la"
next = grandma_house.sword.4

[grandma_house.sword.4]
#       |-----------------------|
line1 = "grotte au Nord-Ouest du"
line2 = "village. Il n'est pas"
line3 = "très commode mais"
next = grandma_house.sword.5

[grandma_house.sword.5]
#       |-----------------------|
line1 = "il pourra sûrement"
line2 = "t'aider."


