-- Minillosaur egg: a small papillosaur that comes from an egg.
-- This enemy is usually be generated by a bigger one.

-- Properties
life = 2
damage = 2
sprite = "enemies/minillosaur"
sprite_animation = "egg"
size = {24, 32}
origin = {12, 20}
attack_consequences = {
  sword = "custom",
  others = "ignored"
}

-- State
in_egg = nil

-- The enemy appears: create its movement
function event_appear()

  in_egg = true
  x, y = sol.enemy.get_position()
  hero_x, hero_y = sol.map.hero_get_position()
  angle = sol.main.get_angle(x, y, hero_x, hero_y)
  m = sol.main.temporal_movement_create(120, angle, 1500)
  sol.main.movement_set_property(m, "smooth", false)
  sol.enemy.start_movement(m)
end

-- The enemy was stopped for some reason and should restart
function event_restart()

  if in_egg then
    sprite = sol.enemy.get_sprite()
    sol.main.sprite_set_animation("in_egg")
  end
end

-- An obstacle is reached: in the egg state, break the egg
function event_obstacle_reached()

  sprite = sol.enemy.get_sprite()
  if sol.main.sprite_get_animation(sprite) == "egg" then
    break_egg()
  end
end

-- The movement is finished: in the egg state, break the egg
function event_movement_finished(movement)
  -- same thing as when an obstacle is reached
  event_obstacle_reached()
end

-- The enemy receives an attack whose consequence is "custom"
function event_custom_attack_received(attack, sprite)

  if attack == "sword" and sol.main.sprite_get_animation(sprite) == "egg" then
    -- the egg is hit by the sword
    break_egg()
    sol.main.play_sound("monster_hurt")
  end
  return 0 -- don't remove any life points
end

-- Starts breaking the egg
function break_egg()

  sprite = sol.enemy.get_sprite()
  sol.enemy.stop_movement()
  sol.main.sprite_set_animation(sprite, "egg_breaking")
end

--  The animation of a sprite is finished
function event_sprite_animation_finished(sprite, animation)

  -- if the egg was breaking, make the minillosaur go
  if animation == "egg_breaking" then
    sol.main.sprite_set_animation(sprite, "walking")
    sol.enemy.set_size(16, 16)
    sol.enemy.set_origin(8, 12)
    sol.enemy.snap_to_grid()
    m = sol.main.path_finding_movement_create(40)
    sol.enemy.start_movement(m)
    sol.enemy.set_default_attack_consequences()
    in_egg = false
  end
end

