#ifndef ZSDX_TRANSPORTABLE_ITEM_TYPE_H
#define ZSDX_TRANSPORTABLE_ITEM_TYPE_H

/**
 * Types of transportable items.
 */
enum TransportableItemType {

  TRANSPORTABLE_ITEM_POT               = 0,
  TRANSPORTABLE_ITEM_SKULL             = 1,
  TRANSPORTABLE_ITEM_BUSH              = 2,
  TRANSPORTABLE_ITEM_STONE_SMALL_WHITE = 3,
  TRANSPORTABLE_ITEM_STONE_SMALL_BLACK = 4,

  // not implemented
  TRANSPORTABLE_ITEM_STONE_BIG_WHITE   = 5,
  TRANSPORTABLE_ITEM_STONE_BIG_BLACK   = 6,

  //  TRANSPORTABLE_ITEM_SIGN              = 7,
};

#endif
