#!/bin/bash

# This script converts one or several .wav files into .ogg, using the command oggenc.

if [ $# == 0 ]; then
  echo "Usage: $0 file.wav ..."
  exit 1
fi

for f in $*; do
  output=`echo $f | sed -e 's/\.wav$/.ogg/'`
  oggenc -o $output $f
done

