#!/bin/bash
cd editor
mvn package
cp target/solarus-editor.jar .
keytool -genkey -keystore ../solaruskeystore -alias solaruskey

jarsigner -keystore ../solaruskeystore solarus-editor.jar solaruskey
mv solarus-editor.jar ..
cd ..

