#!/bin/bash

mkdir export
git archive -o export/tools.tar HEAD .
cd export
tar xvf tools.tar
rm tools.tar
./compile
jar cvmf manifest.mf solarus-editor.jar org
# keytool -genkey -keystore ../solaruskeystore -alias solaruskey
# jarsigner -keystore ../solaruskeystore ini4j.jar solaruskey
jarsigner -keystore ../solaruskeystore solarus-editor.jar solaruskey
scp solarus-editor.jar solarus@solarus-engine.org:www/editor/
# scp ini4j.jar solarus@solarus-engine.org:www/editor/
cd ..
rm -rf export
